name: restaurant_picker
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_fortune_wheel: ^1.3.1
  url_launcher: ^6.0.20
  google_maps_flutter: ^2.7.0
  geolocator: ^12.0.0
  http: ^1.2.2
  carousel_slider: ^4.2.1
  flutter_spinkit: ^5.2.1
  flutter_onboarding_slider: ^1.0.11
  firebase_core: ^3.3.0
  firebase_auth: ^5.1.4
  firebase_ui_auth: ^1.13.1
  firebase_ui_oauth_google: ^1.3.3
  google_generative_ai: ^0.4.5
  intl: ^0.19.0
  flutter_chat_ui: ^1.6.14
  path_provider: ^2.1.4
  open_filex: ^4.4.0
  mime: ^1.0.5
  file_picker: ^8.0.7
  image_picker: ^1.1.2
  permission_handler: ^11.3.1
  flutter_listfilter: ^0.0.5
  filter_list: ^1.0.3
  rubber: ^1.1.0
  desktop_webview_auth: ^0.0.15
  animated_text_kit: ^4.2.2
  google_fonts: ^6.2.1
  flutter_markdown: ^0.7.3+1
  markdown: ^7.2.2
  pay: ^2.0.0
  cloud_firestore: ^5.2.1
  provider: ^6.1.2
  google_places_autocomplete_text_field: ^0.1.3
  uuid: ^4.4.2
  carousel_slider_plus: ^7.0.0
  smart_select: ^4.3.3
  choice: ^2.3.2
  weekday_selector: ^1.1.0
  flutter_google_maps_webservices: ^1.1.1
  modal_bottom_sheet: ^3.0.0
  google_maps_flutter_platform_interface: ^2.9.0
  flutter_dotenv: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_native_splash: ^2.4.1

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/food/
    - assets/banners/
    - .env
  fonts:
    - family: Pacifico
      fonts:
        - asset: fonts/Pacifico-Regular.ttf
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Regular.ttf
    - family: AbrilFatface
      fonts:
        - asset: fonts/AbrilFatface-Regular.ttf

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/splash.gif
  android: true
  ios: true
