// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBma-CCLHYWR9pBAgrMHDYn4aOyQZR5RdE',
    appId: '1:311208916992:web:f330feb057c8d02f9640e5',
    messagingSenderId: '311208916992',
    projectId: 'restaurant-picker-aiot',
    authDomain: 'restaurant-picker-aiot.firebaseapp.com',
    storageBucket: 'restaurant-picker-aiot.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCyCXKoi4SpOAm5ueSAro6nJZeem932SAk',
    appId: '1:311208916992:android:d85102bf6b4bf20e9640e5',
    messagingSenderId: '311208916992',
    projectId: 'restaurant-picker-aiot',
    storageBucket: 'restaurant-picker-aiot.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCcXu64OAGvMqOgyB-tdqgMsdVZhCNiC98',
    appId: '1:311208916992:ios:d94946def463cb1a9640e5',
    messagingSenderId: '311208916992',
    projectId: 'restaurant-picker-aiot',
    storageBucket: 'restaurant-picker-aiot.appspot.com',
    iosBundleId: 'com.example.restaurantPicker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCcXu64OAGvMqOgyB-tdqgMsdVZhCNiC98',
    appId: '1:311208916992:ios:d94946def463cb1a9640e5',
    messagingSenderId: '311208916992',
    projectId: 'restaurant-picker-aiot',
    storageBucket: 'restaurant-picker-aiot.appspot.com',
    iosBundleId: 'com.example.restaurantPicker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBma-CCLHYWR9pBAgrMHDYn4aOyQZR5RdE',
    appId: '1:311208916992:web:c4b316402d1a69909640e5',
    messagingSenderId: '311208916992',
    projectId: 'restaurant-picker-aiot',
    authDomain: 'restaurant-picker-aiot.firebaseapp.com',
    storageBucket: 'restaurant-picker-aiot.appspot.com',
  );
}
